# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'end.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_end(object):
    def setupUi(self, end):
        end.setObjectName("end")
        end.resize(300, 505)
        end.setMinimumSize(QtCore.QSize(300, 0))
        end.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label = QtWidgets.QLabel(end)
        self.label.setGeometry(QtCore.QRect(0, -20, 311, 531))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("주문성공.jpg"))
        self.label.setObjectName("label")

        self.retranslateUi(end)
        QtCore.QMetaObject.connectSlotsByName(end)

    def retranslateUi(self, end):
        _translate = QtCore.QCoreApplication.translate
        end.setWindowTitle(_translate("end", "배달의민족"))
